import { MAIL_SERVICE, OPERATOR, STUDIO } from "./brand";
import type { Contact, DemoState, DraftKind, DraftMessage, RelationshipStage } from "./types";

export const STAGE_META: Record<
  RelationshipStage,
  { color: string; chip: string; segment: string }
> = {
  "New inquiry": {
    color: "text-accent-dark",
    chip: "bg-accent-light text-accent-dark",
    segment: "New inquiry",
  },
  "Quote out": {
    color: "text-[#8a5a28]",
    chip: "bg-[#f3e6d4] text-[#8a5a28]",
    segment: "Quote out",
  },
  "In project": {
    color: "text-[#2f6b4a]",
    chip: "bg-[#e4efe8] text-[#2f6b4a]",
    segment: "In project",
  },
  "Re-engage": {
    color: "text-[#5c534c]",
    chip: "bg-[#ece7e2] text-[#5c534c]",
    segment: "Re-engage",
  },
};

export const KIND_FROM_STAGE: Record<RelationshipStage, DraftKind> = {
  "New inquiry": "inquiry",
  "Quote out": "quote",
  "In project": "project",
  "Re-engage": "reengage",
};

export const DEFAULT_CONTACTS: Contact[] = [
  {
    id: "priya",
    displayName: "Priya Shah",
    firstName: "Priya",
    stage: "Quote out",
    segment: "Quote out",
    focus: "Kitchen remodel · peninsula option",
    need: "The $48k peninsula proposal — she went quiet after the number",
    whyToday: "Proposal has sat 11 days with no reply",
    lastTouch: "Proposal emailed · 11 days ago",
    dueToday: true,
  },
  {
    id: "marcus",
    displayName: "Marcus Bell",
    firstName: "Marcus",
    stage: "New inquiry",
    segment: "New inquiry",
    focus: "Showroom visit · peninsula questions",
    need: "Saturday walk-in — sketched his existing run, no first note yet",
    whyToday: "Walked in Saturday — no first note yet",
    lastTouch: "Showroom · Saturday",
    dueToday: true,
  },
  {
    id: "camille",
    displayName: "Camille Ward",
    firstName: "Camille",
    stage: "Re-engage",
    segment: "Re-engage",
    focus: "Primary bath wrap · three years quiet",
    need: "Finished the bath in 2023; life got busy; powder room was the next thought",
    whyToday: "Re-engage — 3 weeks since last list activity",
    lastTouch: "Opened a studio email · 3 weeks ago",
    dueToday: true,
  },
  {
    id: "june",
    displayName: "June Okada",
    firstName: "June",
    stage: "In project",
    segment: "In project",
    focus: "Primary bath · tile delay",
    need: "Tile slipped a week; she should hear the new window from Elena, not the GC",
    whyToday: "Mid-project check-in after the delay",
    lastTouch: "Site update · 4 days ago",
    dueToday: false,
  },
  {
    id: "theo",
    displayName: "Theo Ramirez",
    firstName: "Theo",
    stage: "Re-engage",
    segment: "Re-engage",
    focus: "Kitchen wrap · one year in",
    need: "Anniversary window — how the kitchen is living, and he already referred Sam",
    whyToday: "One year since walkthrough",
    lastTouch: "Final walkthrough · 12 months ago",
    dueToday: false,
  },
  {
    id: "hannah",
    displayName: "Hannah Cole",
    firstName: "Hannah",
    stage: "Quote out",
    segment: "Quote out",
    focus: "Quartz lead times",
    need: "She asked a specific lead-time question; the answer changed (3–4 weeks, not 8)",
    whyToday: "Warm question still unanswered",
    lastTouch: "Email from Hannah · 3 days ago",
    dueToday: true,
  },
  {
    id: "sam",
    displayName: "Sam Whitaker",
    firstName: "Sam",
    stage: "New inquiry",
    segment: "New inquiry",
    focus: "Referral from Theo Ramirez",
    need: "Theo named him this week for a bath — intro still unsent",
    whyToday: "Referral intro still unsent",
    lastTouch: "Theo mentioned Sam · this week",
    dueToday: true,
  },
  {
    id: "lila",
    displayName: "Lila Nguyen",
    firstName: "Lila",
    stage: "In project",
    segment: "In project",
    focus: "Design presentation Thursday",
    need: "Confirm Thursday at 10; two layouts and the one budget-changing decision",
    whyToday: "Confirm time and send the agenda",
    lastTouch: "Mood boards shared · Monday",
    dueToday: false,
  },
  {
    id: "owen",
    displayName: "Owen Park",
    firstName: "Owen",
    stage: "Re-engage",
    segment: "Re-engage",
    focus: "Powder room · “next year”",
    need: "Said powder room next year at kitchen wrap; fall is a quieter slot",
    whyToday: "Seasonal nudge while the idea is still warm",
    lastTouch: "Kitchen wrap · 8 months ago",
    dueToday: false,
  },
  {
    id: "riley",
    displayName: "Riley Chen",
    firstName: "Riley",
    stage: "Re-engage",
    segment: "Re-engage",
    focus: "Rental kitchen · small footprint",
    need: "Asked if we take rentals last year; never booked",
    whyToday: "Quiet inquiry that never converted",
    lastTouch: "DM · last spring",
    dueToday: false,
  },
  {
    id: "sofia",
    displayName: "Sofia Trent",
    firstName: "Sofia",
    stage: "Quote out",
    segment: "Quote out",
    focus: "Kitchen + mudroom · waiting on numbers",
    need: "Asked for a revised allowance on hardware; draft is ready",
    whyToday: "Revised quote sitting 6 days",
    lastTouch: "Revised PDF · 6 days ago",
    dueToday: false,
  },
  {
    id: "eli",
    displayName: "Eli Frost",
    firstName: "Eli",
    stage: "Re-engage",
    segment: "Re-engage",
    focus: "Kitchen install · wrapped last year",
    need: "Cabinets went in last fall; no check-in since punch list",
    whyToday: "Post-project quiet",
    lastTouch: "Punch list · 11 months ago",
    dueToday: false,
  },
  {
    id: "nina",
    displayName: "Nina Brooks",
    firstName: "Nina",
    stage: "Quote out",
    segment: "Quote out",
    focus: "Galley kitchen · lighting allowance",
    need: "Quote sent; waiting on her partner to look at the lighting line",
    whyToday: "Quote sitting",
    lastTouch: "Proposal · 9 days ago",
    dueToday: false,
  },
  {
    id: "adeel",
    displayName: "Adeel Khan",
    firstName: "Adeel",
    stage: "Quote out",
    segment: "Quote out",
    focus: "Kitchen island · seating for four",
    need: "Asked for a second option at a lower millwork number",
    whyToday: "Revised option not sent",
    lastTouch: "Studio visit · 2 weeks ago",
    dueToday: false,
  },
  {
    id: "tess",
    displayName: "Tess Molina",
    firstName: "Tess",
    stage: "Quote out",
    segment: "Quote out",
    focus: "Bath + linen · tile hold",
    need: "Loved the zellige; quote includes a 6-week tile lead",
    whyToday: "Quote out, no reply",
    lastTouch: "PDF · 5 days ago",
    dueToday: false,
  },
  {
    id: "grant",
    displayName: "Grant Ives",
    firstName: "Grant",
    stage: "Quote out",
    segment: "Quote out",
    focus: "Mudroom · dog wash",
    need: "Number landed high; he asked if we can phase the bench",
    whyToday: "Scope question unanswered",
    lastTouch: "Email · 8 days ago",
    dueToday: false,
  },
  {
    id: "yuki",
    displayName: "Yuki Mori",
    firstName: "Yuki",
    stage: "Quote out",
    segment: "Quote out",
    focus: "Kitchen refresh · keep the layout",
    need: "Wants new fronts only; quote is sitting while they travel",
    whyToday: "Out of town, quote still open",
    lastTouch: "Proposal · 16 days ago",
    dueToday: false,
  },
  {
    id: "paulie",
    displayName: "Paulie Dunn",
    firstName: "Paulie",
    stage: "Quote out",
    segment: "Quote out",
    focus: "Butler’s pantry",
    need: "Asked for a hardware board with the quote; hasn’t opened it",
    whyToday: "Quote unopened",
    lastTouch: "Proposal · 4 days ago",
    dueToday: false,
  },
  {
    id: "nora",
    displayName: "Nora Velez",
    firstName: "Nora",
    stage: "Re-engage",
    segment: "Re-engage",
    focus: "Kitchen wrap · 2019",
    need: "Referred a neighbor last year; we never circled back",
    whyToday: "Quiet client, warm referral history",
    lastTouch: "Holiday card · last December",
    dueToday: false,
  },
  {
    id: "chris",
    displayName: "Chris Lang",
    firstName: "Chris",
    stage: "Re-engage",
    segment: "Re-engage",
    focus: "Bath remodel · 2022",
    need: "Mentioned a kitchen “someday” at the final walkthrough",
    whyToday: "Someday is still sitting in the notes",
    lastTouch: "Walkthrough · 2022",
    dueToday: false,
  },
  {
    id: "bea",
    displayName: "Bea Ortiz",
    firstName: "Bea",
    stage: "Re-engage",
    segment: "Re-engage",
    focus: "Laundry + bath · paused",
    need: "Paused for a move; list still has her in Re-engage",
    whyToday: "Move settled, no note since",
    lastTouch: "Pause email · 7 months ago",
    dueToday: false,
  },
  {
    id: "dev",
    displayName: "Dev Patel",
    firstName: "Dev",
    stage: "Re-engage",
    segment: "Re-engage",
    focus: "Kitchen · first consult 2024",
    need: "Came in once, never quoted; still on the list",
    whyToday: "Consult that never became a quote",
    lastTouch: "Studio visit · 14 months ago",
    dueToday: false,
  },
];

const SIGN_OFF = `${OPERATOR.name}\n${STUDIO.name}`;

export const DEFAULT_MESSAGES: DraftMessage[] = [
  {
    id: "msg-priya",
    contactId: "priya",
    kind: "quote",
    channel: "email",
    subject: "The peninsula proposal — still here if you want to trim it",
    body: `Hi Priya — the kitchen proposal has been sitting about a week and a half, and I didn’t want the number to be the last word.\n\nThe peninsula is the piece that moved budget. If that’s the pause, we can keep the run and drop the seating, or phase the lighting. Same plan, smaller first check.\n\nNo rush — I just didn’t want a $48k PDF to go quiet without a human note.\n\n${SIGN_OFF}`,
    status: "queued",
    sendWindow: MAIL_SERVICE.sendWindow,
  },
  {
    id: "msg-marcus",
    contactId: "marcus",
    kind: "inquiry",
    channel: "email",
    subject: "Peninsula notes from Saturday",
    body: `Hi Marcus — good to meet you in the studio on Saturday. I sketched the peninsula against your existing run so you can see how the seating would feel without moving the sink.\n\nIf a 20-minute follow-up would help, I have Tuesday or Thursday late morning — bring the photo of the current counter if you have it.\n\n${SIGN_OFF}`,
    status: "queued",
    sendWindow: MAIL_SERVICE.sendWindow,
  },
  {
    id: "msg-camille",
    contactId: "camille",
    kind: "reengage",
    channel: "email",
    subject: "The bath, three years on — and that powder room",
    body: `Hi Camille — hope you’ve been doing well since we finished the primary bath.\n\nWe know life gets busy, and it can be hard to carve out time for the next room. You mentioned a powder room when we wrapped, and I didn’t want that to just sit in the notes.\n\nIf anything has come up — or if you’ve been wondering whether it’s worth sketching — a single studio visit usually tells you a lot. Fall is a quieter slot for us.\n\nWarmly,\n${SIGN_OFF}`,
    status: "queued",
    sendWindow: MAIL_SERVICE.sendWindow,
  },
  {
    id: "msg-hannah",
    contactId: "hannah",
    kind: "quote",
    channel: "email",
    subject: "Quartz lead times — the short version",
    body: `Hi Hannah — on the quartz you liked: current lead is 3–4 weeks, not the 8 I mentioned in passing. If we lock the slab this week, we stay on your original start.\n\nI can hold two slabs until Friday if you want to see them in person before we commit.\n\n${SIGN_OFF}`,
    status: "queued",
    sendWindow: MAIL_SERVICE.sendWindow,
  },
  {
    id: "msg-sam",
    contactId: "sam",
    kind: "inquiry",
    channel: "email",
    subject: "Theo thought we should meet",
    body: `Hi Sam — Theo Ramirez suggested I reach out. We did his kitchen last year; he mentioned you might be looking at a bath.\n\nIf a short studio visit is useful, I keep Thursday afternoons for first conversations — no pitch, just whether we’re a fit.\n\n${SIGN_OFF}`,
    status: "queued",
    sendWindow: MAIL_SERVICE.sendWindow,
  },
  {
    id: "msg-june",
    contactId: "june",
    kind: "project",
    channel: "email",
    subject: "Tile delay — here’s the new window",
    body: `Hi June — the tile is now promised for the week of the 24th. Install holds after that; nothing else on your bath moves without you seeing it first.\n\nI’ll be on site Thursday if you want to walk the layout before the tile lands.\n\n${SIGN_OFF}`,
    status: "queued",
    sendWindow: MAIL_SERVICE.sendWindow,
  },
  {
    id: "msg-theo",
    contactId: "theo",
    kind: "reengage",
    channel: "email",
    subject: "One year in — how is the kitchen living?",
    body: `Hi Theo — it’s been a year since we wrapped the kitchen. Curious how it’s living: anything you’d change, anything the next project should steal.\n\nNo agenda other than that — and thank you for sending Sam our way.\n\n${SIGN_OFF}`,
    status: "queued",
    sendWindow: MAIL_SERVICE.sendWindow,
  },
  {
    id: "msg-sofia",
    contactId: "sofia",
    kind: "quote",
    channel: "email",
    subject: "Hardware allowance — the revised number",
    body: `Hi Sofia — here’s the revised hardware allowance we talked about. It brings the kitchen + mudroom back in line with the number you were comfortable with, without changing the layout.\n\nIf the PDF looks right, we can lock it this week and keep your start.\n\n${SIGN_OFF}`,
    status: "queued",
    sendWindow: MAIL_SERVICE.sendWindow,
  },
  {
    id: "msg-lila",
    contactId: "lila",
    kind: "project",
    channel: "email",
    subject: "Thursday’s design presentation",
    body: `Hi Lila — confirming Thursday at 10 for the design presentation. We’ll walk two layouts, the hardware board, and the one decision that actually changes budget.\n\nAgenda attached in spirit: 45 minutes, then you keep the boards.\n\n${SIGN_OFF}`,
    status: "queued",
    sendWindow: MAIL_SERVICE.sendWindow,
  },
];

export function createSeedState(): DemoState {
  return {
    contacts: DEFAULT_CONTACTS.map((contact) => ({ ...contact })),
    messages: DEFAULT_MESSAGES.map((message) => ({ ...message })),
  };
}

export const MOCK_PROVIDERS_ENABLED =
  process.env.NEXT_PUBLIC_USE_MOCK_PROVIDERS !== "false";
